#!/bin/bash -l
#
#$ -N DFTB
#$ -pe smp 2
#$ -cwd
#$ -q ddu.q@gpu-28.cluster.lifesci.dundee.ac.uk
#$ -q ddu.q@gpu-30.compute.dundee.ac.uk
#$ -q ddu.q@gpu-26.compute.dundee.ac.uk

#qsub -R y -mods l_hard m_mem_free 16G
mkdir -p files_dat/
export LD_PRELOAD=/FMOPhore/QM_runs/lib/libgfortran.so.3
/FMOPhore/QM_runs/rungms input.inp 01 1 >& output.log
mv *dat files_dat/.
find . -size 0 -delete

